force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Aggregate_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Queries_Limit__c</fullName>
    <description>Returns the total number of aggregate queries that can be processed with SOQL query statements.
See getLimitAggregateQueries() documented below: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Aggregate Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The nam of the Apex Class which generated the log. Since Exception.getStackTraceString() does not work in managed packages, this can be used to give at least some context of where the log was generated.</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Callouts_Limit__c.field-meta.xml
<CustomField>
    <fullName>Callouts_Limit__c</fullName>
    <description>Returns the total number of Web service statements that can be processed.
See getLimitCallouts() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Callouts Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Details the current execution context when the log was generated.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</description>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time__c</fullName>
    <description>Returns the CPU time (in milliseconds) that has been used in the current transaction.
See getCpuTime() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/CPU_Time_Limit__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time_Limit__c</fullName>
    <description>Returns the maximum CPU time (in milliseconds) that can be used in a transaction.
See getLimitCpuTime() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>CPU Time Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows_Limit__c</fullName>
    <description>Returns the total number of records that can be processed with any statement that counts against DML limits, such as DML statements, the database.EmptyRecycleBin method, and other methods.
See getLimitDMLRows() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>DML Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Statements_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements_Limit__c</fullName>
    <description>Returns the total number of DML statements or the database.EmptyRecycleBin methods that can be called.
See getLimitDMLStatements() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>DML Statements Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Email_Invocations_Limit__c.field-meta.xml
<CustomField>
    <fullName>Email_Invocations_Limit__c</fullName>
    <description>Returns the total number of email invocation (such as sendEmail) that can be called.
See getLimitEmailInvocations() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Email Invocations Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Future_Calls_Limit__c.field-meta.xml
<CustomField>
    <fullName>Future_Calls_Limit__c</fullName>
    <description>Returns the total number of methods with the future annotation that can be executed (not necessarily completed).
See getLimitFutureCalls() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Future Calls Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Heap_Size__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size__c</fullName>
    <description>Returns the approximate amount of memory (in bytes) that has been used for the heap.
See getHeapSize() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Heap Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Heap_Size_Limit__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size_Limit__c</fullName>
    <description>Returns the total amount of memory (in bytes) that can be used for the heap.
See getLimitHeapSize() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Heap Size Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Immediate_Platform_Event_Publish_Limit__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Platform_Event_Publish_Limit__c</fullName>
    <description>Returns the total number of EventBus.publish statements that can be called for platform events configured to publish immediately.
See getLimitPublishImmediateDML() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Immediate Platform Event Publish Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Logged_At__c.field-meta.xml
<CustomField>
    <fullName>Logged_At__c</fullName>
    <description>Shows when the log was generated. 
Different from Created Date, which shows when the log was published.</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Aggregate_Queries__c.field-meta.xml
<CustomField>
    <fullName>Num_Aggregate_Queries__c</fullName>
    <description>Returns the number of aggregate queries that have been processed with any SOQL query statement.
See getAggregateQueries() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Callouts__c.field-meta.xml
<CustomField>
    <fullName>Num_Callouts__c</fullName>
    <description>Returns the number of Web service statements that have been processed.
See getCallouts() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Rows__c</fullName>
    <description>Returns the number of records that have been processed with any statement that counts against DML limits, such as DML statements, the Database.emptyRecycleBin method, and other methods.
See getDMLRows() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Statements__c</fullName>
    <description>Returns the number of DML statements (such as insert, update or the database.EmptyRecycleBin method) that have been called.
See getDMLStatements() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Email_Invocations__c.field-meta.xml
<CustomField>
    <fullName>Num_Email_Invocations__c</fullName>
    <description>Returns the number of email invocations (such as sendEmail) that have been called.
See getEmailInvocations() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Future_Calls__c.field-meta.xml
<CustomField>
    <fullName>Num_Future_Calls__c</fullName>
    <description>Returns the number of methods with the future annotation that have been executed (not necessarily completed).
See getFutureCalls() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Future Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Immediate_Platform_Event_Publish_Limit__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Platform_Event_Publish_Limit__c</fullName>
    <label>Immediate Platform Event Publish Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Aggregate_Queries__c.field-meta.xml
<CustomField>
    <fullName>Num_Aggregate_Queries__c</fullName>
    <label>Num Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Callouts__c.field-meta.xml
<CustomField>
    <fullName>Num_Callouts__c</fullName>
    <label>Num Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Rows__c</fullName>
    <label>Num DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Statements__c</fullName>
    <label>Num DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Email_Invocations__c.field-meta.xml
<CustomField>
    <fullName>Num_Email_Invocations__c</fullName>
    <label>Num Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Future_Calls__c.field-meta.xml
<CustomField>
    <fullName>Num_Future_Calls__c</fullName>
    <label>Num Future Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Logger.cls
@RestResource(urlMapping='/log')
global without sharing abstract class Logger {
	static final Integer MAX_LENGTH = Log__c.Message__c.getDescribe()?.getLength();
	static Integer Sequence = 1;

	@TestVisible
	static List<Log_Event__e> PendingLogs = new List<Log_Event__e>();

	@TestVisible
	static List<Log_Event__e> PublishedLogs = new List<Log_Event__e>();

	@TestVisible
	static Log_Setting__c Settings = Logger.getLogSettings();

	@TestVisible
	static LoggingLevel Threshold {
		get {
			Boolean matchesSettings = Logger.Threshold?.name()?.equalsIgnoreCase(Logger.Settings?.Level__c);
			if (matchesSettings != true) {
				LoggingLevel newLevel = (LoggingLevel) EnumUtils.valueOf(Settings?.Level__c, LoggingLevel.class);
				Logger.Threshold = (newLevel != null) ? newLevel : LoggingLevel.NONE;
			}
			return Logger.Threshold;
		}
		private set;
	}

	// **** GLOBAL **** //
	@AuraEnabled
	global static void publish() {
		Logger.PublishedLogs.addAll(Logger.PendingLogs);
		DB.Dml.doPublish(Logger.PendingLogs);
		Logger.PendingLogs.clear();
	}

	global static void log(LoggingLevel level, Type apexClass, Object messageObj) {
		// Note: Since Exception.getStackTraceString() returns null in managed packages,
		// callers can use the optional `apexClass` param for rudimentary stack tracing
		if (Logger.isEnabled(level)) {
			System.debug(level, messageObj);
			Logger.PendingLogs.add(
				new Log_Event__e(
					Aggregate_Queries_Limit__c = Limits.getLimitAggregateQueries(),
					Apex_Class__c = String.valueOf(apexClass),
                    Callouts_Limit__c = Limits.getLimitCallouts(),
					Context__c = System.Request.getCurrent().getQuiddity()?.name(),
                    CPU_Time__c = Limits.getCpuTime(),
                    CPU_Time_Limit__c = Limits.getLimitCpuTime(),
                    DML_Rows_Limit__c = Limits.getLimitDMLRows(),
                    DML_Statements_Limit__c = Limits.getLimitDMLStatements(),
                    Email_Invocations_Limit__c = Limits.getLimitEmailInvocations(),
                    Future_Calls_Limit__c = Limits.getLimitFutureCalls(),
                    Heap_Size__c = Limits.getHeapSize(),
                    Heap_Size_Limit__c = Limits.getLimitHeapSize(),
                    Immediate_Platform_Event_Publish_Limit__c = Limits.getLimitPublishImmediateDML(),
					Level__c = level?.name(),
					Logged_At__c = DateTime.now(),
					Message__c = String.valueOf(messageObj)?.abbreviate(MAX_LENGTH),
                    Num_Aggregate_Queries__c = Limits.getAggregateQueries(),
                    Num_Callouts__c = Limits.getCallouts(),
                    Num_DML_Rows__c = Limits.getDMLRows(),
                    Num_DML_Statements__c = Limits.getDMLStatements(),
                    Num_Email_Invocations__c = Limits.getEmailInvocations(),
                    Num_Future_Calls__c = Limits.getFutureCalls(),
                    Num_Immediate_Platform_Event_Publish__c = Limits.getPublishImmediateDML(),
                    Num_Push_Notifications__c = Limits.getMobilePushApexCalls(),
                    Num_QueryLocator_Rows__c = Limits.getQueryLocatorRows(),
                    Num_Queueable_Jobs__c = Limits.getQueueableJobs(),
                    Num_SOQL_Queries__c = Limits.getQueries(),
                    Num_SOQL_Query_Rows__c = Limits.getQueryRows(),
                    Num_SOSL_Queries__c = Limits.getSoslQueries(),
                    Push_Notifications_Limit__c = Limits.getLimitMobilePushApexCalls(),
                    QueryLocator_Row_Limit__c = Limits.getLimitQueryLocatorRows(),
                    Queueable_Job_Limit__c = Limits.getLimitQueueableJobs(),
					Running_User__c = UserInfo.getUserId(),
					Sequence__c = Logger.Sequence++,
                    SOQL_Queries_Limit__c = Limits.getLimitQueries(),
                    SOQL_Query_Row_Limit__c = Limits.getLimitQueryRows(),
                    SOSL_Query_Limit__c = Limits.getLimitSoslQueries(),
					Stack_Trace__c = Logger.getStackTrace()?.abbreviate(MAX_LENGTH),
					Transaction_Id__c = System.Request.getCurrent()?.getRequestId()
				)
			);
		}
	}

	global static void log(LoggingLevel level, Object message) {
		Logger.log(level, null, message);
	}

	global static void log(Object message) {
		// Defaults to FINEST
		Logger.finest(message);
	}

	@AuraEnabled
	global static void log(List<LogInput> logInputs) {
		// Primarily used by external sources (ie., invocable, aura, api)
		for (LogInput logInput : logInputs) {
			logInput.log();
		}
	}

	global static void error(Type apexClass, Object message) {
		Logger.log(LoggingLevel.ERROR, apexClass, message);
	}

	global static void error(Object message) {
		Logger.error(null, message);
	}

	global static void warn(Type apexClass, Object message) {
		Logger.log(LoggingLevel.WARN, apexClass, message);
	}

	global static void info(Type apexClass, Object message) {
		Logger.log(LoggingLevel.INFO, apexClass, message);
	}

	global static void info(Object message) {
		Logger.info(null, message);
	}

	global static void warn(Object message) {
		Logger.warn(null, message);
	}

	global static void debug(Type apexClass, Object message) {
		Logger.log(LoggingLevel.DEBUG, apexClass, message);
	}

	global static void debug(Object message) {
		Logger.debug(null, message);
	}

	global static void fine(Type apexClass, Object message) {
		Logger.log(LoggingLevel.FINE, apexClass, message);
	}

	global static void fine(Object message) {
		Logger.fine(null, message);
	}

	global static void finer(Type apexClass, Object message) {
		Logger.log(LoggingLevel.FINER, apexClass, message);
	}

	global static void finer(Object message) {
		Logger.finer(null, message);
	}

	global static void finest(Type apexClass, Object message) {
		Logger.log(LoggingLevel.FINEST, apexClass, message);
	}

	global static void finest(Object message) {
		Logger.finest(null, message);
	}

	@HttpPost
	global static void log() {
		// Exposes the logger to external solutions
		try {
			String requestBody = RestContext.request?.requestBody?.toString();
			List<LogInput> logInputs = (List<LogInput>) JSON.deserialize(requestBody, List<LogInput>.class);
			Logger.log(logInputs);
			Logger.publish();
			RestContext.response.statusCode = 200;
		} catch (Exception error) {
			RestContext.response.statusCode = 500;
			RestContext.response.responseBody = Blob.valueOf(
				JSON.serialize(new Map<String, String>{
					 'message' => String.valueOf(error) 
				})
			);
		}
	}

	// **** PRIVATE **** //
	@TestVisible
	static Log_Setting__c getLogSettings() {
		// Returns a Custom Setting record that corresponds to the running user/their profile/their organization
		Log_Setting__c logSettings = Log_Setting__c.getInstance();
		LoggingLevel level = (LoggingLevel) EnumUtils.valueOf(logSettings?.Level__c, LoggingLevel.class);
		if (level == null) {
			// Either no org defaults exist, or it has a missing/invalid Level__c
			// If this happens, upsert a valid settings record and set as org default
			Log_Setting__c defaultSettings = Log_Setting__c.getOrgDefaults();
			defaultSettings.Enabled__c = (defaultSettings.Enabled__c) ? defaultSettings.Enabled__c : false;
			defaultSettings.Level__c = LoggingLevel.NONE?.name();
			defaultSettings.SetupOwnerId = UserInfo.getOrganizationId();
			upsert defaultSettings;
			logSettings = defaultSettings;
		}
		return logSettings;
	}

	static Boolean isEnabled(LoggingLevel currentLevel) {
		// Returns TRUE if logging is enabled, and the current level is
		// as/more severe than the minimum threshold specified in Custom Settings.
		// This is done to mimick the way traditional debug logs are set up in Salesforce.
		// Severity is indicated by the LoggingLevel enum's ordinal(), in order:
		// NONE(0), INTERNAL(1), FINEST(2), FINER(3), FINE(4), DEBUG(5), INFO(6), WARN(7), ERROR(8)
		Integer thresholdSeverity = (Logger.Threshold != null) ? Logger.Threshold?.ordinal() : 0;
		Integer currentSeverity = (currentLevel != null) ? currentLevel?.ordinal() : 0;
		Boolean results =
			Logger.Settings?.Enabled__c == true &&
			thresholdSeverity > 0 && // Prevent logging when Logger.Threshold == NONE
			currentSeverity >= thresholdSeverity;
		return results;
	}

	static String getStackTrace() {
		return new LogException().sourceStackTrace();
	}

	// **** INNER **** //
	global class LogInput {
		@InvocableVariable
		global String logLevelName;

		@InvocableVariable
		global String logMessage;

		public void log() {
			LoggingLevel level = (LoggingLevel) EnumUtils.valueOf(logLevelName, LoggingLevel.class);
			if (level != null) {
				Logger.log(level, logMessage);
			}
		}
	}

	private class LogException extends Exception {
		private String sourceStackTrace() {
			List<String> stackTraceLines = new List<String>();
			for (String stackTraceLine : this.getStackTraceString().split('\n')) {
				// Do not include this class in the stack trace info
				final String loggerPrefix = 'Class.' + String.valueOf(Logger.class) + '.';
				if (!stackTraceLine?.startsWith(loggerPrefix)) {
					stackTraceLines.add(stackTraceLine);
				}
			}
			return String.join(stackTraceLines, '\n');
		}
	}
}