force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Aggregate_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Queries_Limit__c</fullName>
    <description>Returns the total number of aggregate queries that can be processed with SOQL query statements.
See getLimitAggregateQueries() documented below: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Aggregate Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Callouts_Limit__c.field-meta.xml
<CustomField>
    <fullName>Callouts_Limit__c</fullName>
    <description>Returns the total number of Web service statements that can be processed.
See getLimitCallouts() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Callouts Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Details the current execution context when the log was generated.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</description>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time__c</fullName>
    <description>Returns the CPU time (in milliseconds) that has been used in the current transaction.
See getCpuTime() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/CPU_Time_Limit__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time_Limit__c</fullName>
    <description>Returns the maximum CPU time (in milliseconds) that can be used in a transaction.
See getLimitCpuTime() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>CPU Time Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows_Limit__c</fullName>
    <description>Returns the total number of records that can be processed with any statement that counts against DML limits, such as DML statements, the database.EmptyRecycleBin method, and other methods.
See getLimitDMLRows() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>DML Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Statements_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements_Limit__c</fullName>
    <description>Returns the total number of DML statements or the database.EmptyRecycleBin methods that can be called.
See getLimitDMLStatements() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>DML Statements Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Email_Invocations_Limit__c.field-meta.xml
<CustomField>
    <fullName>Email_Invocations_Limit__c</fullName>
    <description>Returns the total number of email invocation (such as sendEmail) that can be called.
See getLimitEmailInvocations() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Email Invocations Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Future_Calls_Limit__c.field-meta.xml
<CustomField>
    <fullName>Future_Calls_Limit__c</fullName>
    <description>Returns the total number of methods with the future annotation that can be executed (not necessarily completed).
See getLimitFutureCalls() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Future Calls Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Heap_Size__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size__c</fullName>
    <description>Returns the approximate amount of memory (in bytes) that has been used for the heap.
See getHeapSize() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Heap Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Heap_Size_Limit__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size_Limit__c</fullName>
    <description>Returns the total amount of memory (in bytes) that can be used for the heap.
See getLimitHeapSize() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Heap Size Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Immediate_Platform_Event_Publish_Limit__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Platform_Event_Publish_Limit__c</fullName>
    <description>Returns the total number of EventBus.publish statements that can be called for platform events configured to publish immediately.
See getLimitPublishImmediateDML() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Immediate Platform Event Publish Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Include_Limits_Data__c.field-meta.xml
<CustomField>
    <fullName>Include_Limits_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Limits Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Logged_At__c.field-meta.xml
<CustomField>
    <fullName>Logged_At__c</fullName>
    <description>Shows when the log was generated. 
Different from Created Date, which shows when the log was published.</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Aggregate_Queries__c.field-meta.xml
<CustomField>
    <fullName>Num_Aggregate_Queries__c</fullName>
    <description>Returns the number of aggregate queries that have been processed with any SOQL query statement.
See getAggregateQueries() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Callouts__c.field-meta.xml
<CustomField>
    <fullName>Num_Callouts__c</fullName>
    <description>Returns the number of Web service statements that have been processed.
See getCallouts() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Rows__c</fullName>
    <description>Returns the number of records that have been processed with any statement that counts against DML limits, such as DML statements, the Database.emptyRecycleBin method, and other methods.
See getDMLRows() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Statements__c</fullName>
    <description>Returns the number of DML statements (such as insert, update or the database.EmptyRecycleBin method) that have been called.
See getDMLStatements() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Email_Invocations__c.field-meta.xml
<CustomField>
    <fullName>Num_Email_Invocations__c</fullName>
    <description>Returns the number of email invocations (such as sendEmail) that have been called.
See getEmailInvocations() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Future_Calls__c.field-meta.xml
<CustomField>
    <fullName>Num_Future_Calls__c</fullName>
    <description>Returns the number of methods with the future annotation that have been executed (not necessarily completed).
See getFutureCalls() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Future Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Num_Immediate_Platform_Event_Publish__c.field-meta.xml
<CustomField>
    <fullName>Num_Immediate_Platform_Event_Publish__c</fullName>
    <description>Returns the number of EventBus.publish calls that have been made for platform events configured to publish immediately.
See getPublishImmediateDML() documented below:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Num Immediate Platform Event Publish</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Immediate_Platform_Event_Publish_Limit__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Platform_Event_Publish_Limit__c</fullName>
    <label>Immediate Platform Event Publish Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Include_Limits_Data__c.field-meta.xml
<CustomField>
    <fullName>Include_Limits_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Limits Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Aggregate_Queries__c.field-meta.xml
<CustomField>
    <fullName>Num_Aggregate_Queries__c</fullName>
    <label>Num Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Callouts__c.field-meta.xml
<CustomField>
    <fullName>Num_Callouts__c</fullName>
    <label>Num Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Rows__c</fullName>
    <label>Num DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>Num_DML_Statements__c</fullName>
    <label>Num DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Email_Invocations__c.field-meta.xml
<CustomField>
    <fullName>Num_Email_Invocations__c</fullName>
    <label>Num Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Num_Future_Calls__c.field-meta.xml
<CustomField>
    <fullName>Num_Future_Calls__c</fullName>
    <label>Num Future Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LogGenerator.cls
public class LogGenerator {
	List<Log_Event__e> events;

	public LogGenerator(List<Log_Event__e> events) { 
		this.events = events;
	}

	public void createLogRecords() {
		List<Log__c> logs = new List<Log__c>();
		for (Log_Event__e event : this.events) {
			Log__c log = new Log__c(
				Aggregate_Queries_Limit__c = event?.Aggregate_Queries_Limit__c,
				Callouts_Limit__c = event?.Callouts_Limit__c,
				Context__c = event?.Context__c,
				CPU_Time__c = event?.CPU_Time__c,
				CPU_Time_Limit__c = event?.CPU_Time_Limit__c,
				DML_Rows_Limit__c = event?.DML_Rows_Limit__c,
				DML_Statements_Limit__c = event?.DML_Statements_Limit__c,
				Email_Invocations_Limit__c = event?.Email_Invocations_Limit__c,
				Future_Calls_Limit__c = event?.Future_Calls_Limit__c,
				Heap_Size__c = event?.Heap_Size__c,
				Heap_Size_Limit__c = event?.Heap_Size_Limit__c,
				Immediate_Platform_Event_Publish_Limit__c = event?.Immediate_Platform_Event_Publish_Limit__c,
				Include_Limits_Data__c = event?.Include_Limits_Data__c,
				Level__c = event?.Level__c,
				Logged_At__c = event?.Logged_At__c,
				Message__c = event?.Message__c,
				Num_Aggregate_Queries__c = event?.Num_Aggregate_Queries__c,
				Num_Callouts__c = event?.Num_Callouts__c,
				Num_DML_Rows__c = event?.Num_DML_Rows__c,
				Num_DML_Statements__c = event?.Num_DML_Statements__c,
				Num_Email_Invocations__c = event?.Num_Email_Invocations__c,
				Num_Future_Calls__c = event?.Num_Future_Calls__c,
				Num_Immediate_Platform_Event_Publish__c = event?.Num_Immediate_Platform_Event_Publish__c,
				Num_Push_Notifications__c = event?.Num_Push_Notifications__c,
				Num_QueryLocator_Rows__c = event?.Num_QueryLocator_Rows__c,
				Num_Queueable_Jobs__c = event?.Num_Queueable_Jobs__c,
				Num_SOQL_Queries__c = event?.Num_SOQL_Queries__c,
				Num_SOQL_Query_Rows__c = event?.Num_SOQL_Query_Rows__c,
				Num_SOSL_Queries__c = event?.Num_SOSL_Queries__c,
				Push_Notifications_Limit__c = event?.Push_Notifications_Limit__c,
				QueryLocator_Row_Limit__c = event?.QueryLocator_Row_Limit__c,
				Queueable_Job_Limit__c = event?.Queueable_Job_Limit__c,
				Running_User__c = event?.Running_User__c,
				Sequence__c = event?.Sequence__c,
				SOQL_Queries_Limit__c = event?.SOQL_Queries_Limit__c,
				SOQL_Query_Row_Limit__c = event?.SOQL_Query_Row_Limit__c,
				SOSL_Query_Limit__c = event?.SOSL_Query_Limit__c,
				Source__c = event?.Source__c,
				Stack_Trace__c = event?.Stack_Trace__c,
				Transaction_Id__c = event?.Transaction_Id__c
			);
			logs.add(log); 
		}
		Database.insert(logs, false);
	}
}