force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LogUtils_Test.cls
@IsTest 
private class LogUtils_Test {
    @IsTest 
    static void shouldLogErrors() {
        DmlResult result = new MockDmlResult(
            new List<DmlResult.Error>(), 
            false, 
            DmlMock.generateFakeId(Account.SObjectType), 
            Database.SaveResult.class
        );

        Test.startTest();
        LogUtils.logErrors(new List<DmlResult>{result});
        Logger.publish(); 
        Test.stopTest();

        Integer numLogs = (Integer) [SELECT COUNT(Id) FROM Log__c][0].get('expr0');
        System.assertEquals(1, numLogs, 'Wrong # of Pending Logs');
    }

    @IsTest 
    static void shouldNotLogIfNoErrors() {
        DmlResult result = new MockDmlResult(
            new List<DmlResult.Error>(), 
            true, 
            DmlMock.generateFakeId(Account.SObjectType), 
            Database.SaveResult.class
        );

        Test.startTest();
        LogUtils.logErrors(new List<DmlResult>{result});
        Logger.publish();
        Test.stopTest();

        Integer numLogs = (Integer) [SELECT COUNT(Id) FROM Log__c][0].get('expr0');
        System.assertEquals(0, numLogs, 'Wrong # of Pending Logs');
    }

    @TestSetup 
    static void setup() {
        insert new Log_Setting__c(
            Enabled__c = true, 
            Level__c = System.LoggingLevel.FINEST.name(),
            SetupOwnerId = UserInfo.getUserId()
        ); 
    }
}